baseURL = 'https://natansessays.com/'
languageCode = 'en-us'
title = 'Essays by Natan Freeman'
theme = "PaperMod"
enableRobotsTXT = true

[params]
  env = "production"
  description = "Essays by Natan Freeman on technology, AI, history, and more"
  github_repo = "https://github.com/NatanFreeman/essays"
  defaultTheme = "auto"
  disableThemeToggle = true
  DateFormat = "January 2, 2006"
  disableSpecial1stPost = true
  comments = true

  [[params.socialIcons]]
    name = "mastodon"
    url = "https://mastodon.social/@natanfreeman"

  [params.editPost]
    URL = "https://github.com/NatanFreeman/essays/blob/main/content"
    Text = "Suggest Changes"
    appendFilePath = true

  [params.analytics.google]
    SiteVerificationTag = "7pmwM2-PY41jO397FyTwrCslrwbwqYO9M6MjlGIbE7k"